displayName: Rewrite Body
summary: Rewrites the HTTP response body by replacing a search regex by a replacement string.
type: middleware
import: github.com/containous/plugin-rewritebody
compatibility: TODO
testData:
  rewrites:
    - regex: "bar"
      replacement: "foo"
